[build]
  command = "npm run build:all"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev:vite"
  port = 8888
  functions="netlify/functions"
  targetPort = 5173
  framework = "#auto"
  autoLaunch = true